name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v3
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: BeCrista # Substitua pelo seu username
          outputs: dist/snake.svg
      - name: Set up Git for GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push Snake animation to the output branch
        run: |
          git add dist/snake.svg
          git commit -m "Generated Snake Animation" || echo "No changes to commit"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
